baseURL = 'https://indig0-zero.github.io/'
locale = 'en-us'
title = 'Shake it !!!'
theme = "reimu"

defaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "en-us"

[markup]
  [markup.highlight]
    noClasses = false