baseURL = 'https://indig0-zero.github.io/'
locale = 'en-us'
title = 'Shake it !!!'
theme = "reimu"

defaultContentLanguage = "vi"
hasCJKLanguage = true

[markup]
  [markup.highlight]
    noClasses = false